In [1]:
from build_df import build_dataframe
from analyze_files import build_folder_summary

df_meta = build_dataframe()

df_meta

Number of .txt files found:  2540

,source_path,temp_folder_label,deltaT_label,T_plate_label,series_id,channel_raw,channel_norm,pressure_raw_label,pressure_corr_mpa,point_type,pair_id,role,is_complete_pair,reference_zero_id
0,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
1,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
2,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
3,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
4,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2535,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2536,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2537,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2538,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2539,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...

In [2]:
df_summary = build_folder_summary(df_meta)

df_summary

Building summary: 100%|██████████| 1270/1270 [00:34<00:00, 37.08it/s]

,folder,pressure,dT,Tp,y_signal,x_signal,role,path_y,path_x,ref,low_quality,y_quality,y_quality_ref,x_quality,x_quality_ref
0,DT0_T23_15,0.5,0.0,23,-0.831463,0.161859,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.954192,0.968495,0.977005,0.968314
1,DT0_T23_15,0.5,0.0,23,-0.771594,0.136736,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.971030,0.976281,0.979902,0.968858
2,DT0_T23_15,0.5,0.0,23,-0.829784,0.153464,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.945863,0.971392,0.979540,0.970306
3,DT0_T23_15,0.5,0.0,23,-0.805183,0.156881,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.950389,0.970849,0.982437,0.966685
4,DT0_T23_15,0.5,0.0,23,-0.786022,0.153799,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.973927,0.968858,0.973746,0.967047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,DT45.7_T75_27,9.0,45.7,75,-17.365373,6.411286,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687934,0.689945,0.687934
1176,DT45.7_T75_27,9.0,45.7,75,-17.367951,6.392017,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687934,0.689397,0.687934
1177,DT45.7_T75_27,9.0,45.7,75,-17.361069,6.389999,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.687020,0.687569,0.690311,0.687934
1178,DT45.7_T75_27,9.0,45.7,75,-17.328483,6.416023,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687751,0.690128,0.688300
1179,DT45.7_T75_27,9.0,45.7,75,-17.349070,6.377746,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687569,0.689945,0.688300

In [3]:
df_summary.isnull().sum()

folder           0
pressure         0
dT               0
Tp               0
y_signal         0
x_signal         0
role             0
path_y           0
path_x           0
ref              0
low_quality      0
y_quality        0
y_quality_ref    0
x_quality        0
x_quality_ref    0
dtype: int64

In [4]:
df_summary[df_summary["ref"].notna()]

,folder,pressure,dT,Tp,y_signal,x_signal,role,path_y,path_x,ref,low_quality,y_quality,y_quality_ref,x_quality,x_quality_ref
0,DT0_T23_15,0.5,0.0,23,-0.831463,0.161859,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.954192,0.968495,0.977005,0.968314
1,DT0_T23_15,0.5,0.0,23,-0.771594,0.136736,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.971030,0.976281,0.979902,0.968858
2,DT0_T23_15,0.5,0.0,23,-0.829784,0.153464,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.945863,0.971392,0.979540,0.970306
3,DT0_T23_15,0.5,0.0,23,-0.805183,0.156881,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.950389,0.970849,0.982437,0.966685
4,DT0_T23_15,0.5,0.0,23,-0.786022,0.153799,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.973927,0.968858,0.973746,0.967047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,DT45.7_T75_27,9.0,45.7,75,-17.365373,6.411286,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687934,0.689945,0.687934
1176,DT45.7_T75_27,9.0,45.7,75,-17.367951,6.392017,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687934,0.689397,0.687934
1177,DT45.7_T75_27,9.0,45.7,75,-17.361069,6.389999,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.687020,0.687569,0.690311,0.687934
1178,DT45.7_T75_27,9.0,45.7,75,-17.328483,6.416023,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687751,0.690128,0.688300
1179,DT45.7_T75_27,9.0,45.7,75,-17.349070,6.377746,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,True,0.686837,0.687569,0.689945,0.688300

In [18]:
df_base_for_training = df_summary[df_summary["ref"].notna()][["pressure", "dT", "Tp", "y_signal", "x_signal", "role", "low_quality", "x_quality", "x_quality_ref", "y_quality", "y_quality_ref"]]
df_base_for_training[df_base_for_training["x_quality"] > 0.9]

,pressure,dT,Tp,y_signal,x_signal,role,low_quality,x_quality,x_quality_ref,y_quality,y_quality_ref
0,0.5,0.0,23,-0.831463,0.161859,EDA;pressure_calibration;joint_regression;,False,0.977005,0.968314,0.954192,0.968495
1,0.5,0.0,23,-0.771594,0.136736,EDA;pressure_calibration;joint_regression;,False,0.979902,0.968858,0.971030,0.976281
2,0.5,0.0,23,-0.829784,0.153464,EDA;pressure_calibration;joint_regression;,False,0.979540,0.970306,0.945863,0.971392
3,0.5,0.0,23,-0.805183,0.156881,EDA;pressure_calibration;joint_regression;,False,0.982437,0.966685,0.950389,0.970849
4,0.5,0.0,23,-0.786022,0.153799,EDA;pressure_calibration;joint_regression;,False,0.973746,0.967047,0.973927,0.968858
5,0.5,0.0,23,-0.793378,0.171897,EDA;pressure_calibration;joint_regression;,False,0.979721,0.971754,0.965598,0.973565
6,0.5,0.0,23,-0.788794,0.159464,EDA;pressure_calibration;joint_regression;,False,0.978635,0.968858,0.975014,0.973384
7,0.5,0.0,23,-0.802716,0.150582,EDA;pressure_calibration;joint_regression;,False,0.983523,0.970306,0.960891,0.970487
8,0.5,0.0,23,-0.791378,0.147470,EDA;pressure_calibration;joint_regression;,False,0.981351,0.970125,0.964150,0.967047
9,0.5,0.0,23,-0.804693,0.159648,EDA;pressure_calibration;joint_regression;,False,0.979359,0.972479,0.963245,0.968676
20,0.0,0.0,23,-0.233718,-0.231926,EDA;joint_regression;repeatability_test;,False,0.960529,0.968314,0.921963,0.968495
21,0.0,0.0,23,-0.218495,-0.234701,EDA;joint_regression;repeatability_test;,False,0.966142,0.968858,0.954554,0.976281
22,0.0,0.0,23,-0.224649,-0.237054,EDA;joint_regression;repeatability_test;,False,0.963788,0.970306,0.933551,0.971392
23,0.0,0.0,23,-0.219055,-0.210818,EDA;joint_regression;repeatability_test;,False,0.970487,0.966685,0.929024,0.970849
24,0.0,0.0,23,-0.222860,-0.209341,EDA;joint_regression;repeatability_test;,False,0.965417,0.967047,0.934275,0.968858
25,0.0,0.0,23,-0.218479,-0.225050,EDA;joint_regression;repeatability_test;,False,0.964150,0.971754,0.944595,0.973565
26,0.0,0.0,23,-0.214567,-0.208906,EDA;joint_regression;repeatability_test;,False,0.970487,0.968858,0.945682,0.973384
27,0.0,0.0,23,-0.238350,-0.225666,EDA;joint_regression;repeatability_test;,False,0.967952,0.970306,0.948035,0.970487
28,0.0,0.0,23,-0.229032,-0.228681,EDA;joint_regression;repeatability_test;,False,0.965236,0.970125,0.942423,0.967047
29,0.0,0.0,23,-0.232653,-0.231684,EDA;joint_regression;repeatability_test;,False,0.966504,0.972479,0.938801,0.968676
30,1.0,0.0,23,-1.399305,0.394122,EDA;pressure_calibration;joint_regression;,False,0.987507,0.968314,0.998733,0.968495
31,1.0,0.0,23,-1.385230,0.369115,EDA;pressure_calibration;joint_regression;,False,0.991852,0.968858,0.998370,0.976281
32,1.0,0.0,23,-1.402096,0.375023,EDA;pressure_calibration;joint_regression;,False,0.990585,0.970306,0.998552,0.971392
33,1.0,0.0,23,-1.394965,0.392159,EDA;pressure_calibration;joint_regression;,False,0.991490,0.966685,0.998552,0.970849
34,1.0,0.0,23,-1.381904,0.416139,EDA;pressure_calibration;joint_regression;,False,0.992033,0.967047,0.998552,0.968858
35,1.0,0.0,23,-1.369565,0.390539,EDA;pressure_calibration;joint_regression;,False,0.990947,0.971754,0.998552,0.973565
36,1.0,0.0,23,-1.381359,0.378343,EDA;pressure_calibration;joint_regression;,False,0.990042,0.968858,0.998370,0.973384
37,1.0,0.0,23,-1.388208,0.378563,EDA;pressure_calibration;joint_regression;,False,0.991309,0.970306,0.998370,0.970487
38,1.0,0.0,23,-1.400731,0.377904,EDA;pressure_calibration;joint_regression;,False,0.991128,0.970125,0.998370,0.967047
39,1.0,0.0,23,-1.399880,0.374876,EDA;pressure_calibration;joint_regression;,False,0.989861,0.972479,0.998370,0.968676

In [6]:
df_base_for_training[df_base_for_training["role"].str.contains("EDA")].info()

<class 'pandas.DataFrame'>
RangeIndex: 1180 entries, 0 to 1179
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       1180 non-null   float64
 1   dT             1180 non-null   float64
 2   Tp             1180 non-null   int64
 3   y_signal       1180 non-null   float64
 4   x_signal       1180 non-null   float64
 5   role           1180 non-null   str
 6   low_quality    1180 non-null   bool
 7   x_quality      1180 non-null   float64
 8   x_quality_ref  1180 non-null   float64
 9   y_quality      1180 non-null   float64
 10  y_quality_ref  1180 non-null   float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 93.5 KB

In [7]:
df_base_for_training[df_base_for_training["role"].str.contains("joint_regression")].info()

<class 'pandas.DataFrame'>
RangeIndex: 1180 entries, 0 to 1179
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       1180 non-null   float64
 1   dT             1180 non-null   float64
 2   Tp             1180 non-null   int64
 3   y_signal       1180 non-null   float64
 4   x_signal       1180 non-null   float64
 5   role           1180 non-null   str
 6   low_quality    1180 non-null   bool
 7   x_quality      1180 non-null   float64
 8   x_quality_ref  1180 non-null   float64
 9   y_quality      1180 non-null   float64
 10  y_quality_ref  1180 non-null   float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 93.5 KB

In [8]:

df_base_for_training[df_base_for_training["role"].str.contains("pressure_calibration")].info()

<class 'pandas.DataFrame'>
Index: 110 entries, 0 to 119
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       110 non-null    float64
 1   dT             110 non-null    float64
 2   Tp             110 non-null    int64
 3   y_signal       110 non-null    float64
 4   x_signal       110 non-null    float64
 5   role           110 non-null    str
 6   low_quality    110 non-null    bool
 7   x_quality      110 non-null    float64
 8   x_quality_ref  110 non-null    float64
 9   y_quality      110 non-null    float64
 10  y_quality_ref  110 non-null    float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 9.6 KB

In [9]:

df_base_for_training[df_base_for_training["role"].str.contains("repeatability_test")].info()

<class 'pandas.DataFrame'>
Index: 60 entries, 20 to 1089
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       60 non-null     float64
 1   dT             60 non-null     float64
 2   Tp             60 non-null     int64
 3   y_signal       60 non-null     float64
 4   x_signal       60 non-null     float64
 5   role           60 non-null     str
 6   low_quality    60 non-null     bool
 7   x_quality      60 non-null     float64
 8   x_quality_ref  60 non-null     float64
 9   y_quality      60 non-null     float64
 10  y_quality_ref  60 non-null     float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 5.2 KB