In [1]:
from build_df import build_dataframe
from analyze_files import build_folder_summary

df_meta = build_dataframe()

df_meta

Number of .txt files found:  2540

Building summary: 100%|██████████| 1270/1270 [00:31<00:00, 39.85it/s]
Detecting swap: 100%|██████████| 9/9 [00:00<00:00, 310.14it/s]

          folder   slope_y   slope_x  opposite_sign  valid  swapped
0     DT0_T23_15 -1.453084  0.549332           True   True    False
1  DT16.2_T42_02 -1.774434  0.650597           True   True    False
2  DT20.5_T45_19 -1.497622  0.623812           True   True    False
3  DT24.7_T50_20 -1.413159  0.724107           True   True    False
4  DT27.4_T55_16 -1.330457  0.512827           True   True    False
5    DT33_T60_21 -1.504822  0.648777           True   True    False
6  DT37.5_T65_25 -1.381913  0.735752           True   True    False
7  DT41.8_T70_26 -1.384337  0.618830           True   True    False
8  DT45.7_T75_27 -1.392947  0.754692           True   True    False
Number of .txt files found:  2540

,source_path,temp_folder_label,deltaT_label,T_plate_label,series_id,channel_raw,channel_norm,pressure_raw_label,pressure_corr_mpa,point_type,pair_id,role,is_complete_pair,reference_zero_id
0,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
1,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
2,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
3,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
4,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2535,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2536,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2537,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2538,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2539,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...

In [2]:
df_summary = build_folder_summary(df_meta)

df_summary

Building summary: 100%|██████████| 1270/1270 [00:34<00:00, 36.43it/s]

,folder,pressure,dT,Tp,y_signal,x_signal,role,path_y,path_x,ref
0,DT0_T23_15,0.5,0.0,23,-0.844084,0.143175,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
1,DT0_T23_15,0.5,0.0,23,-0.793819,0.125935,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
2,DT0_T23_15,0.5,0.0,23,-0.828605,0.137130,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
3,DT0_T23_15,0.5,0.0,23,-0.819826,0.147640,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
4,DT0_T23_15,0.5,0.0,23,-0.816836,0.138004,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
...,...,...,...,...,...,...,...,...,...,...
1265,DT45.7_T75_27,9.0,45.7,75,-12.354308,5.886038,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1266,DT45.7_T75_27,9.0,45.7,75,-12.321572,6.632287,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1267,DT45.7_T75_27,9.0,45.7,75,-11.660526,6.371934,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1268,DT45.7_T75_27,9.0,45.7,75,-12.084479,5.998025,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1269,DT45.7_T75_27,9.0,45.7,75,-12.233640,6.357925,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...

In [3]:
df_summary.isnull().sum()

folder       0
pressure     0
dT           0
Tp           0
y_signal     0
x_signal     0
role         0
path_y       0
path_x       0
ref         90
dtype: int64

In [ ]:
df_summary[df_summary["ref"].notna()]

,folder,pressure,dT,Tp,y_signal,x_signal,role,path_y,path_x,ref
0,DT0_T23_15,0.5,0.0,23,-0.844084,0.143175,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
1,DT0_T23_15,0.5,0.0,23,-0.793819,0.125935,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
2,DT0_T23_15,0.5,0.0,23,-0.828605,0.137130,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
3,DT0_T23_15,0.5,0.0,23,-0.819826,0.147640,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
4,DT0_T23_15,0.5,0.0,23,-0.816836,0.138004,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
...,...,...,...,...,...,...,...,...,...,...
1265,DT45.7_T75_27,9.0,45.7,75,-12.354308,5.886038,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1266,DT45.7_T75_27,9.0,45.7,75,-12.321572,6.632287,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1267,DT45.7_T75_27,9.0,45.7,75,-11.660526,6.371934,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1268,DT45.7_T75_27,9.0,45.7,75,-12.084479,5.998025,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...
1269,DT45.7_T75_27,9.0,45.7,75,-12.233640,6.357925,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...

In [10]:
df_summary[df_summary["ref"].notna()][["pressure", "dT", "Tp", "y_signal", "x_signal", "role"]]

,pressure,dT,Tp,y_signal,x_signal,role
0,0.5,0.0,23,-0.844084,0.143175,EDA;pressure_calibration;joint_regression;
1,0.5,0.0,23,-0.793819,0.125935,EDA;pressure_calibration;joint_regression;
2,0.5,0.0,23,-0.828605,0.137130,EDA;pressure_calibration;joint_regression;
3,0.5,0.0,23,-0.819826,0.147640,EDA;pressure_calibration;joint_regression;
4,0.5,0.0,23,-0.816836,0.138004,EDA;pressure_calibration;joint_regression;
...,...,...,...,...,...,...
1265,9.0,45.7,75,-12.354308,5.886038,EDA;joint_regression;
1266,9.0,45.7,75,-12.321572,6.632287,EDA;joint_regression;
1267,9.0,45.7,75,-11.660526,6.371934,EDA;joint_regression;
1268,9.0,45.7,75,-12.084479,5.998025,EDA;joint_regression;
1269,9.0,45.7,75,-12.233640,6.357925,EDA;joint_regression;